-- ============================================================
-- Database: CSE 340 Project — Assignment 2
-- Full SQL Script: Task 1 & Task 2
-- ============================================================

-- =============================
-- 1️⃣ Create ENUM Type
-- =============================
CREATE TYPE public.account_type AS ENUM (
  'Client',
  'Employee',
  'Admin'
);

ALTER TYPE public.account_type
OWNER TO cse340;

-- =============================
-- 2️⃣ Create Tables
-- =============================

-- 2a. Classification Table
CREATE TABLE public.classification (
  classification_id INT GENERATED BY DEFAULT AS IDENTITY,
  classification_name VARCHAR NOT NULL,
  CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

-- 2b. Inventory Table
CREATE TABLE public.inventory (
  inv_id INT GENERATED BY DEFAULT AS IDENTITY,
  inv_make VARCHAR NOT NULL,
  inv_model VARCHAR NOT NULL,
  inv_year INT NOT NULL,
  inv_description TEXT NOT NULL,
  inv_image VARCHAR NOT NULL,
  inv_thumbnail VARCHAR NOT NULL,
  inv_price NUMERIC(9,2) NOT NULL,
  inv_miles INT NOT NULL,
  inv_color VARCHAR NOT NULL,
  classification_id INT NOT NULL,
  CONSTRAINT inventory_pk PRIMARY KEY (inv_id),
  CONSTRAINT fk_classification FOREIGN KEY (classification_id)
    REFERENCES public.classification(classification_id)
    ON UPDATE CASCADE
    ON DELETE NO ACTION
);

-- 2c. Account Table
CREATE TABLE public.account (
  account_id INT GENERATED BY DEFAULT AS IDENTITY,
  account_firstname VARCHAR NOT NULL,
  account_lastname VARCHAR NOT NULL,
  account_email VARCHAR NOT NULL,
  account_password VARCHAR NOT NULL,
  account_type account_type NOT NULL DEFAULT 'Client',
  CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

-- =============================
-- 3️⃣ Insert Classification Data
-- =============================
INSERT INTO public.classification (classification_name)
VALUES
('Custom'),
('Sport'),
('SUV'),
('Truck'),
('Sedan');

-- =============================
-- 4️⃣ Insert Inventory Data
-- =============================
INSERT INTO public.inventory (
  inv_make, inv_model, inv_year, inv_description,
  inv_image, inv_thumbnail, inv_price,
  inv_miles, inv_color, classification_id
)
VALUES
('Chevy', 'Camaro', 2018,
 'If you want to look cool this is the car you need! This car has great performance at an affordable price. Own it today!',
 '/images/camaro.jpg', '/images/camaro-tn.jpg', 25000, 101222, 'Silver', 2),

('Batmobile', 'Custom', 2007,
 'Ever want to be a super hero? Now you can with the Batmobile.',
 '/images/batmobile.jpg', '/images/batmobile-tn.jpg', 65000, 29887, 'Black', 1),

('FBI', 'Surveillance Van', 2016,
 'Do you like police shows? You will feel right at home driving this van, comes complete with surveillance equipment for an extra fee of $2,000 a month.',
 '/images/survan.jpg', '/images/survan-tn.jpg', 20000, 19851, 'Brown', 1),

('Dog', 'Car', 1997,
 'Do you like dogs? Well this car is for you straight from the 90s from Aspen, Colorado we have the original Dog Car complete with fluffy ears.',
 '/images/dog-car.jpg', '/images/dog-car-tn.jpg', 35000, 71632, 'White', 1),

('Jeep', 'Wrangler', 2019,
 'The Jeep Wrangler is small and compact with enough power to get you where you want to go. Great for everyday driving as well as off-roading.',
 '/images/wrangler.jpg', '/images/wrangler-tn.jpg', 28045, 41205, 'Yellow', 3),

('Lamborghini', 'Adventador', 2016,
 'This V-12 engine packs a punch in this sporty car. Make sure you wear your seatbelt and obey all traffic laws.',
 '/images/adventador.jpg', '/images/adventador-tn.jpg', 417650, 71003, 'Blue', 2),

('Aerocar International', 'Aerocar', 1963,
 'Are you sick of rush hour traffic? This car converts into an airplane to get you where you are going fast. Only 6 of these were made, get them while they last!',
 '/images/aerocar.jpg', '/images/aerocar-tn.jpg', 700000, 18956, 'Red', 1),

('Monster', 'Truck', 1995,
 'Most trucks are for working, this one is for fun. This beast comes with 60 inch tires giving you traction needed to jump and roll in the mud.',
 '/images/monster-truck.jpg', '/images/monster-truck-tn.jpg', 150000, 3998, 'Purple', 1),

('Cadillac', 'Escalade', 2019,
 'This stylish car is great for any occasion from going to the beach to meeting the president. The luxurious interior makes this car a home away from home.',
 '/images/escalade.jpg', '/images/escalade-tn.jpg', 75195, 41958, 'Black', 4),

('GM', 'Hummer', 2016,
 'Do you have 6 kids and like to go off-roading? The Hummer gives you a huge interior with an engine to get you out of any muddy or rocky situation.',
 '/images/hummer.jpg', '/images/hummer-tn.jpg', 58800, 56564, 'Yellow', 4),

('Mechanic', 'Special', 1964,
 'Not sure where this car came from. However with a little TLC it will run as good as new.',
 '/images/mechanic.jpg', '/images/mechanic-tn.jpg', 100, 200125, 'Rust', 5),

('Ford', 'Model T', 1921,
 'The Ford Model T can be a bit tricky to drive. It was the first car to be put into production. You can get it in any color you want as long as it is black.',
 '/images/model-t.jpg', '/images/model-t-tn.jpg', 30000, 26357, 'Black', 5);

-- Add remaining inventory entries here as needed
-- Ensure inv_year is INTEGER and paths are correct

-- =============================
-- 5️⃣ Task 1: Account Operations
-- =============================

-- 5a. Insert Tony Stark
INSERT INTO public.account (
  account_firstname,
  account_lastname,
  account_email,
  account_password
)
VALUES (
  'Tony',
  'Stark',
  'tony@starkent.com',
  'Iam1ronM@n'
);

-- 5b. Update Tony Stark to Admin
UPDATE public.account
SET account_type = 'Admin'
WHERE account_email = 'tony@starkent.com';

-- 5c. Delete Tony Stark
DELETE FROM public.account
WHERE account_email = 'tony@starkent.com';

-- 5d. Update GM Hummer Description
UPDATE public.inventory
SET inv_description = REPLACE(
  inv_description,
  'small interiors',
  'a huge interior'
)
WHERE inv_make = 'GM'
  AND inv_model = 'Hummer';
